# src/llm/client.py

import json
from typing import Any

import requests


# ==========================================================
# OLLAMA CONFIGURATION
# ==========================================================

OLLAMA_BASE_URL = "http://localhost:11434"

DEFAULT_MODEL = "qwen3:4b"

REQUEST_TIMEOUT = 180


# ==========================================================
# INPUT VALIDATION
# ==========================================================

def _validate_request_inputs(
    prompt: str,
    temperature: float,
) -> None:
    """
    Validate common inputs used by Ollama requests.
    """

    if not isinstance(prompt, str):
        raise TypeError(
            "prompt must be a string."
        )

    if not prompt.strip():
        raise ValueError(
            "Prompt cannot be empty."
        )

    if not 0 <= temperature <= 2:
        raise ValueError(
            "temperature must be between 0 and 2."
        )


# ==========================================================
# SEND REQUEST TO OLLAMA
# ==========================================================

def _send_ollama_request(
    payload: dict[str, Any],
) -> dict[str, Any]:
    """
    Send a request to the Ollama generate endpoint.

    Returns
    -------
    dict
        Raw Ollama response.
    """

    url = (
        f"{OLLAMA_BASE_URL}/api/generate"
    )

    try:

        response = requests.post(
            url,
            json=payload,
            timeout=REQUEST_TIMEOUT,
        )

        response.raise_for_status()

    except requests.exceptions.ConnectionError as error:

        raise RuntimeError(
            "Could not connect to Ollama. "
            "Make sure Ollama is running."
        ) from error

    except requests.exceptions.Timeout as error:

        raise RuntimeError(
            "The Ollama request timed out."
        ) from error

    except requests.exceptions.RequestException as error:

        raise RuntimeError(
            f"Ollama request failed: {error}"
        ) from error

    try:

        result = response.json()

    except requests.exceptions.JSONDecodeError as error:

        raise RuntimeError(
            "Ollama returned an invalid HTTP JSON response."
        ) from error

    if not isinstance(result, dict):

        raise RuntimeError(
            "Ollama returned an unexpected response format."
        )

    if result.get("error"):

        raise RuntimeError(
            f"Ollama error: {result['error']}"
        )

    return result


# ==========================================================
# NORMAL TEXT GENERATION
# ==========================================================

def generate_response(
    prompt: str,
    model: str = DEFAULT_MODEL,
    temperature: float = 0.2,
) -> str:
    """
    Send a prompt to a local Ollama model and return
    the generated text response.

    Parameters
    ----------
    prompt : str
        Prompt sent to the LLM.

    model : str
        Ollama model name.

    temperature : float
        Controls randomness.

    Returns
    -------
    str
        Text generated by the model.
    """

    _validate_request_inputs(
        prompt=prompt,
        temperature=temperature,
    )

    payload = {
        "model": model,

        "prompt": prompt,

        "stream": False,

        # We only need the final answer from Qwen.
        "think": False,

        "options": {
            "temperature": temperature,

            # Prevent excessively long responses.
            "num_predict": 512,
        },
    }

    result = _send_ollama_request(
        payload
    )

    generated_text = result.get(
        "response",
        ""
    )

    if generated_text is None:
        generated_text = ""

    generated_text = generated_text.strip()

    if not generated_text:

        thinking = result.get(
            "thinking",
            ""
        )

        raise RuntimeError(
            "Ollama returned an empty response.\n\n"
            f"Model: {model}\n"
            f"Done: {result.get('done')}\n"
            f"Done reason: {result.get('done_reason')}\n"
            f"Thinking present: {bool(thinking)}\n"
            f"Prompt eval count: "
            f"{result.get('prompt_eval_count')}\n"
            f"Eval count: "
            f"{result.get('eval_count')}"
        )

    return generated_text


# ==========================================================
# STRUCTURED JSON GENERATION
# ==========================================================

def generate_json_response(
    prompt: str,
    model: str = DEFAULT_MODEL,
    temperature: float = 0.1,
) -> dict[str, Any] | list[Any]:
    """
    Generate structured JSON using Ollama and convert
    the response into a Python dictionary or list.

    This function is intended for agent components that
    require machine-readable LLM decisions, such as:

    - dataset understanding
    - EDA planning
    - tool selection
    - insight generation

    Parameters
    ----------
    prompt : str
        Prompt sent to the LLM.

    model : str
        Ollama model name.

    temperature : float
        Controls randomness.

    Returns
    -------
    dict | list
        Parsed JSON response.
    """

    _validate_request_inputs(
        prompt=prompt,
        temperature=temperature,
    )

    payload = {
        "model": model,

        "prompt": prompt,

        "stream": False,

        # Ask Ollama to constrain the output to JSON.
        "format": "json",

        # Qwen3 supports reasoning/thinking.
        # Structured agent calls only need the final result.
        "think": False,

        "options": {
            "temperature": temperature,

            # Enough for structured agent decisions while
            # preventing unnecessarily long generations.
            "num_predict": 512,
        },
    }

    result = _send_ollama_request(
        payload
    )

    generated_text = result.get(
        "response",
        ""
    )

    if generated_text is None:
        generated_text = ""

    generated_text = generated_text.strip()

    # --------------------------------------------------
    # EMPTY RESPONSE DIAGNOSTICS
    # --------------------------------------------------

    if not generated_text:

        thinking = result.get(
            "thinking",
            ""
        )

        raise RuntimeError(
            "Ollama returned an empty JSON response.\n\n"
            f"Model: {model}\n"
            f"Done: {result.get('done')}\n"
            f"Done reason: {result.get('done_reason')}\n"
            f"Thinking present: {bool(thinking)}\n"
            f"Prompt eval count: "
            f"{result.get('prompt_eval_count')}\n"
            f"Eval count: "
            f"{result.get('eval_count')}"
        )

    # --------------------------------------------------
    # CONVERT JSON STRING -> PYTHON OBJECT
    # --------------------------------------------------

    try:

        parsed_response = json.loads(
            generated_text
        )

    except json.JSONDecodeError as error:

        raise RuntimeError(
            "The LLM returned content that could not "
            "be parsed as valid JSON.\n\n"
            f"Raw response:\n{generated_text}"
        ) from error

    # --------------------------------------------------
    # VALIDATE JSON ROOT
    # --------------------------------------------------

    if not isinstance(
        parsed_response,
        (dict, list)
    ):

        raise RuntimeError(
            "The LLM JSON response must contain "
            "a JSON object or array at the root."
        )

    return parsed_response