# src/agents/insight_generator.py

import json
import re
from typing import Any

from src.llm.client import generate_json_response


# ==========================================================
# LANGUAGE SAFETY
# ==========================================================

CAUSAL_PATTERNS = [
    r"\bcauses?\b",
    r"\bcaused by\b",
    r"\bdrives?\b",
    r"\bdriven by\b",
    r"\bleads? to\b",
    r"\bresults? in\b",
    r"\bimpacts?\b",
    r"\binfluences?\b",
    r"\bdetermines?\b",
    r"\bproduces?\b",
]


def _contains_causal_language(
    text: str
) -> bool:
    """
    Detect language that may incorrectly imply causation.

    Correlation-based EDA does not establish causal
    relationships, so these expressions should not appear
    in ordinary correlation insights.
    """

    if not isinstance(text, str):
        return False

    lowered_text = text.lower()

    return any(
        re.search(
            pattern,
            lowered_text
        )
        for pattern in CAUSAL_PATTERNS
    )


def _neutralise_causal_language(
    text: str
) -> str:
    """
    Replace common causal expressions with neutral,
    association-based language.

    This acts as a defensive layer in case the LLM ignores
    the prompt instruction about correlation and causation.
    """

    if not isinstance(text, str):
        return str(text)

    replacements = [
        (
            r"\bmay influence\b",
            "is associated with"
        ),
        (
            r"\binfluences?\b",
            "is associated with"
        ),
        (
            r"\bmay impact\b",
            "is associated with"
        ),
        (
            r"\bimpacts?\b",
            "is associated with"
        ),
        (
            r"\bmay drive\b",
            "is associated with"
        ),
        (
            r"\bdrives?\b",
            "is associated with"
        ),
        (
            r"\bis driven by\b",
            "is associated with"
        ),
        (
            r"\bmay lead to\b",
            "is associated with"
        ),
        (
            r"\bleads? to\b",
            "is associated with"
        ),
        (
            r"\bmay result in\b",
            "is associated with"
        ),
        (
            r"\bresults? in\b",
            "is associated with"
        ),
        (
            r"\bcauses?\b",
            "is associated with"
        ),
        (
            r"\bis caused by\b",
            "is associated with"
        ),
        (
            r"\bdetermines?\b",
            "is associated with"
        ),
        (
            r"\bproduces?\b",
            "is associated with"
        ),
    ]

    cleaned_text = text

    for pattern, replacement in replacements:

        cleaned_text = re.sub(
            pattern,
            replacement,
            cleaned_text,
            flags=re.IGNORECASE,
        )

    return cleaned_text.strip()


# ==========================================================
# SAMPLE SIZE
# ==========================================================

def _estimate_sample_size(
    numerical_summary: dict[str, Any],
    categorical_summary: dict[str, Any],
) -> int | None:
    """
    Estimate the number of analysed observations from
    available statistical summaries.

    Numerical summaries generated by pandas describe()
    normally contain a 'count' field.

    The maximum valid count is used because individual
    columns may contain missing values.
    """

    counts = []

    for statistics in numerical_summary.values():

        if not isinstance(
            statistics,
            dict
        ):
            continue

        count = statistics.get(
            "count"
        )

        if isinstance(
            count,
            (int, float)
        ):

            counts.append(
                int(count)
            )

    if counts:
        return max(counts)

    # Categorical summaries currently do not contain an
    # explicit total row count, so they are not used to
    # estimate sample size unless the numerical summaries
    # provide no usable information.

    return None


# ==========================================================
# INSIGHT GENERATOR
# ==========================================================

def generate_insights(
    numerical_summary: dict[str, Any],
    categorical_summary: dict[str, Any],
    correlation_matrix: dict[str, Any],
    semantic_analysis: dict[str, Any] | None = None,
    target_analysis: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """
    Generate concise analytical insights from statistics
    already calculated by Python.

    Python performs the numerical analysis.
    The LLM is used only to interpret those results.

    Identifier columns are removed before analytical context
    is sent to the LLM.

    The returned text is also checked for causal language so
    correlation-based findings are described as associations.
    """

    # ==================================================
    # NORMALISE INPUTS
    # ==================================================

    numerical_summary = numerical_summary or {}
    categorical_summary = categorical_summary or {}
    correlation_matrix = correlation_matrix or {}
    semantic_analysis = semantic_analysis or {}
    target_analysis = target_analysis or {}

    # ==================================================
    # SEMANTIC INFORMATION
    # ==================================================

    identifier_columns = semantic_analysis.get(
        "identifier_columns",
        []
    )

    target_candidates = semantic_analysis.get(
        "target_candidates",
        []
    )

    feature_columns = semantic_analysis.get(
        "feature_columns",
        []
    )

    identifier_columns = (
        identifier_columns
        if isinstance(identifier_columns, list)
        else []
    )

    target_candidates = (
        target_candidates
        if isinstance(target_candidates, list)
        else []
    )

    feature_columns = (
        feature_columns
        if isinstance(feature_columns, list)
        else []
    )

    # ==================================================
    # REMOVE IDENTIFIERS FROM NUMERICAL ANALYSIS
    # ==================================================

    filtered_numerical_summary = {
        column: statistics
        for column, statistics
        in numerical_summary.items()
        if column not in identifier_columns
    }

    # ==================================================
    # REMOVE IDENTIFIERS FROM CATEGORICAL ANALYSIS
    # ==================================================

    filtered_categorical_summary = {
        column: statistics
        for column, statistics
        in categorical_summary.items()
        if column not in identifier_columns
    }

    # ==================================================
    # REMOVE IDENTIFIERS FROM CORRELATION MATRIX
    # ==================================================

    filtered_correlation_matrix = {}

    for column, relationships in correlation_matrix.items():

        if column in identifier_columns:
            continue

        if not isinstance(
            relationships,
            dict
        ):
            continue

        filtered_relationships = {
            other_column: value
            for other_column, value
            in relationships.items()
            if other_column not in identifier_columns
        }

        filtered_correlation_matrix[
            column
        ] = filtered_relationships

    # ==================================================
    # ESTIMATE SAMPLE SIZE
    # ==================================================

    sample_size = _estimate_sample_size(
        numerical_summary=
            filtered_numerical_summary,

        categorical_summary=
            filtered_categorical_summary,
    )

    small_dataset = (
        sample_size is not None
        and sample_size < 30
    )

    # ==================================================
    # CREATE COMPACT CONTEXT
    # ==================================================

    analytical_context = {
        "numerical":
            filtered_numerical_summary,

        "categorical":
            filtered_categorical_summary,

        "correlations":
            filtered_correlation_matrix,

        "targets":
            target_analysis,

        "metadata": {
            "identifiers":
                identifier_columns,

            "target_candidates":
                target_candidates,

            "features":
                feature_columns,

            "sample_size":
                sample_size,

            "small_dataset":
                small_dataset,
        },
    }

    context_json = json.dumps(
        analytical_context,
        default=str,
        separators=(",", ":"),
    )

    # ==================================================
    # BUILD STRICT PROMPT
    # ==================================================

    prompt = f"""
You are a careful senior data analyst interpreting
statistics calculated by Python.

Your job is to INTERPRET the supplied results.

Use ONLY the information in DATA.

STRICT RULES:

- Never invent statistics.
- Never invent business context.
- Never claim causation from correlation.
- Correlation describes association only.
- Never say a correlated variable causes, drives,
  influences, impacts, determines, produces, leads to,
  or results in another variable.
- Use phrases such as "is associated with",
  "shows a relationship with", or
  "shows a positive/negative association".
- Identifier columns are not analytical features.
- Do not interpret identifiers as meaningful numerical
  variables.
- A target candidate is only a possible target.
- Do not call it a confirmed prediction target.
- Consider sample size when interpreting results.
- If metadata.small_dataset is true, explicitly mention
  that findings should be interpreted cautiously.
- Do not recommend machine-learning models.
- Do not reproduce the supplied statistical objects.
- Every insight must include specific evidence from DATA.
- Keep responses concise.
- Maximum 4 key insights.
- Maximum 2 target insights.
- Maximum 3 cautions.
- Do not output reasoning.
- Do not output markdown.
- Return ONLY the final JSON object.

Return exactly this JSON structure:

{{
  "summary": "maximum two sentences",

  "key_insights": [
    {{
      "title": "short title",
      "insight": "maximum two sentences",
      "evidence": "specific statistic from DATA",
      "importance": "high"
    }}
  ],

  "target_insights": [
    {{
      "target": "target column name",
      "insight": "maximum two sentences",
      "evidence": "specific statistic from DATA"
    }}
  ],

  "data_cautions": [
    "short caution"
  ]
}}

The importance field MUST be one of:
"high", "medium", "low".

DATA:
{context_json}
"""

    # ==================================================
    # GENERATE STRUCTURED RESPONSE
    # ==================================================

    response = generate_json_response(
        prompt=prompt,
        temperature=0.0,
    )

    # ==================================================
    # VALIDATE ROOT RESPONSE
    # ==================================================

    if not isinstance(
        response,
        dict
    ):

        raise ValueError(
            "Insight generator expected "
            "a JSON object."
        )

    # ==================================================
    # SUMMARY
    # ==================================================

    summary = response.get(
        "summary",
        ""
    )

    if not isinstance(
        summary,
        str
    ):

        summary = str(
            summary
        )

    summary = _neutralise_causal_language(
        summary.strip()
    )

    # ==================================================
    # KEY INSIGHTS
    # ==================================================

    raw_key_insights = response.get(
        "key_insights",
        []
    )

    if not isinstance(
        raw_key_insights,
        list
    ):

        raw_key_insights = []

    key_insights = []

    allowed_importance = {
        "high",
        "medium",
        "low",
    }

    for insight in raw_key_insights[:4]:

        if not isinstance(
            insight,
            dict
        ):
            continue

        title = insight.get(
            "title"
        )

        insight_text = insight.get(
            "insight"
        )

        evidence = insight.get(
            "evidence"
        )

        importance = insight.get(
            "importance",
            "medium"
        )

        if not title:
            continue

        if not insight_text:
            continue

        if not evidence:
            continue

        if importance not in allowed_importance:

            importance = "medium"

        insight_text = str(
            insight_text
        ).strip()

        # Defensive post-processing:
        # even if the model ignores the prompt, causal
        # expressions are converted to neutral language.
        if _contains_causal_language(
            insight_text
        ):

            insight_text = (
                _neutralise_causal_language(
                    insight_text
                )
            )

        key_insights.append(
            {
                "title":
                    str(title).strip(),

                "insight":
                    insight_text,

                "evidence":
                    str(evidence).strip(),

                "importance":
                    importance,
            }
        )

    # ==================================================
    # TARGET INSIGHTS
    # ==================================================

    raw_target_insights = response.get(
        "target_insights",
        []
    )

    if not isinstance(
        raw_target_insights,
        list
    ):

        raw_target_insights = []

    target_insights = []

    for insight in raw_target_insights[:2]:

        if not isinstance(
            insight,
            dict
        ):
            continue

        target = insight.get(
            "target"
        )

        insight_text = insight.get(
            "insight"
        )

        evidence = insight.get(
            "evidence"
        )

        if not target:
            continue

        if not insight_text:
            continue

        if not evidence:
            continue

        if (
            target_candidates
            and target not in target_candidates
        ):
            continue

        insight_text = (
            _neutralise_causal_language(
                str(insight_text).strip()
            )
        )

        target_insights.append(
            {
                "target":
                    str(target).strip(),

                "insight":
                    insight_text,

                "evidence":
                    str(evidence).strip(),
            }
        )

    # ==================================================
    # DATA CAUTIONS
    # ==================================================

    raw_cautions = response.get(
        "data_cautions",
        []
    )

    if not isinstance(
        raw_cautions,
        list
    ):

        raw_cautions = []

    data_cautions = []

    for caution in raw_cautions[:3]:

        if caution is None:
            continue

        caution_text = str(
            caution
        ).strip()

        if caution_text:

            data_cautions.append(
                caution_text
            )

    # ==================================================
    # GUARANTEE SMALL-SAMPLE CAUTION
    # ==================================================

    if small_dataset:

        sample_caution = (
            f"The analysis contains only {sample_size} "
            "observations, so statistical relationships "
            "should be interpreted cautiously."
        )

        caution_present = any(
            (
                "sample" in caution.lower()
                or "observation" in caution.lower()
                or "dataset" in caution.lower()
            )
            for caution in data_cautions
        )

        if not caution_present:

            if len(data_cautions) >= 3:

                data_cautions[-1] = (
                    sample_caution
                )

            else:

                data_cautions.append(
                    sample_caution
                )

    # ==================================================
    # RETURN NORMALISED RESULT
    # ==================================================

    return {
        "summary":
            summary,

        "key_insights":
            key_insights,

        "target_insights":
            target_insights,

        "data_cautions":
            data_cautions,
    }