# src/agents/state.py

from typing import Any, TypedDict

import pandas as pd


class AgentState(TypedDict, total=False):
    """
    Shared state used by the Agentic Analytics workflow.

    Every LangGraph node can read values from this state
    and return updates that are merged back into the state.

    The state supports both:

    Phase 1
        Automated dataset analysis and report generation.

    Phase 2
        Conversational analytics over the analysed dataset.
    """

    # ==================================================
    # DATASET
    # ==================================================

    dataset_path: str

    # Original dataset loaded from the source file.
    dataframe: pd.DataFrame

    # Dataset after cleaning.
    cleaned_dataframe: pd.DataFrame


    # ==================================================
    # DATASET UNDERSTANDING
    # ==================================================

    profile: dict[str, Any]

    quality_report: dict[str, Any]


    # ==================================================
    # CLEANING
    # ==================================================

    cleaning_plan: list[dict[str, Any]]

    cleaning_report: dict[str, Any]

    cleaning_validation: dict[str, Any]


    # ==================================================
    # STATISTICAL ANALYSIS
    # ==================================================

    numerical_summary: dict[str, Any]

    categorical_summary: dict[str, Any]

    correlation_matrix: dict[str, Any]

    analysis_results: dict[str, Any]


    # ==================================================
    # SEMANTIC ANALYSIS
    # ==================================================

    # Complete output produced by analyze_semantics().
    semantic_analysis: dict[str, Any]

    # Convenient copies of important semantic groups.
    identifier_columns: list[str]

    target_candidates: list[str]

    feature_columns: list[str]


    # ==================================================
    # EDA PLANNING
    # ==================================================

    # Tasks produced by create_eda_plan().
    analysis_plan: list[dict[str, Any]]


    # ==================================================
    # TOOL EXECUTION
    # ==================================================

    chart_paths: list[str]

    executed_tasks: list[dict[str, Any]]

    skipped_tasks: list[dict[str, Any]]

    execution_errors: list[dict[str, Any]]

    execution_report: dict[str, Any]


    # ==================================================
    # SEMANTIC EXECUTION METADATA
    # ==================================================

    # Semantic information recorded by the executor.
    semantic_metadata: dict[str, Any]


    # ==================================================
    # TARGET ANALYSIS
    # ==================================================

    # Distribution/statistics generated for possible
    # prediction targets.
    target_analysis: dict[str, Any]


    # ==================================================
    # AGENT REASONING / INSIGHTS
    # ==================================================

    # Structured insight-generator output.
    insights: dict[str, Any]


    # ==================================================
    # FINAL REPORT
    # ==================================================

    final_report: str

    report_path: str


    # ==================================================
    # PHASE 2 — CONVERSATIONAL ANALYTICS
    # ==================================================

    # Natural-language question submitted by the user.
    user_question: str

    # Structured interpretation produced by the
    # conversational query analyzer.
    query_analysis: dict[str, Any]

    # Tool-execution plan produced from query_analysis.
    query_plan: list[dict[str, Any]]

    # Deterministic evidence generated by executing the
    # conversational query plan.
    query_execution: dict[str, Any]

    # Final grounded answer returned to the user.
    query_answer: dict[str, Any]


    # ==================================================
    # CONVERSATION METADATA
    # ==================================================

    # Optional history for later multi-turn conversational
    # analytics support.
    conversation_history: list[dict[str, Any]]


    # ==================================================
    # WORKFLOW ERROR TRACKING
    # ==================================================

    errors: list[str]