#statistical_executor.py

"""
Statistical execution engine.

Receives a statistical execution plan from the
Statistical Planner and dispatches the request
to the appropriate statistical function.
"""

from typing import Any

import pandas as pd

from src.tools.statistics import (
    pearson_correlation,
    spearman_correlation,
    independent_t_test,
    chi_square_test,
    anova_test,
    calculate_skewness,
    calculate_kurtosis,
    detect_iqr_outliers,
    confidence_interval_mean,
)


def _require_parameter(
    plan: dict[str, Any],
    key: str,
) -> str:
    """
    Retrieve a required parameter from the execution plan.
    """

    value = plan.get(key)

    if value is None:
        raise ValueError(
            f"Missing '{key}' in execution plan."
        )

    return value


def execute_statistical_plan(
    dataframe: pd.DataFrame,
    plan: dict[str, Any],
) -> dict[str, Any]:
    """
    Execute a statistical plan generated by the
    Statistical Planner.
    """

    tool = plan.get("tool")

    if tool is None:
        raise ValueError(
            "No statistical tool specified."
        )

    # -----------------------------------------
    # Pearson Correlation
    # -----------------------------------------

    if tool == "pearson_correlation":

        column_x = _require_parameter(
            plan,
            "column_x",
        )

        column_y = _require_parameter(
            plan,
            "column_y",
        )

        return pearson_correlation(
            dataframe=dataframe,
            column_x=column_x,
            column_y=column_y,
        )

    raise ValueError(
        f"Unsupported statistical tool: {tool}"
    )


__all__ = [
    "execute_statistical_plan",
]